#########################################
# basic parameters
#########################################
device:
  value: cuda:0
task_name:
  value: SL
  # value: tNTL
  # value: tCUTI
  # value: tSOPHON
domain_src:
  value: visda_t
domain_tgt:
  value: visda_v
patch_value:
  value: default
image_size:
  value: 64
num_classes:
  value: 12

seed:
  value: 2023
batch_size:
  value: 32
num_workers:
  value: 16

pre_split:
  value: True
data_transform:
  value: ntl

#########################################
# parameters for training SL/NTL models
#########################################
teacher_network:
  # value: vgg19
  value: resnet34cmi
teacher_pretrain:
  value: True
  # value: False
train_teacher_scratch:
  value: True
  # value: False
save_train_teacher:
  value: True
  # value: False
pretrained_teacher:
  # value: saved_models/SL_sd.pth
  value: auto
pretrain_epochs:
  value: 20
pretrain_lr:
  value: 0.001
pretrain_momentum:
  value: 0.9
pretrain_weight_decay:
  value: 0.0001
#########################################
# additional parameters for NTL
#########################################
NTL_alpha:
  value: 0.1
NTL_beta:
  value: 0.1
#########################################
# additional parameters for CUTI
#########################################
CUTI_alpha:
  value: 0.1
#########################################
# additional parameters for SOPHON
#########################################
SOPHON_ways:
  value: 10
SOPHON_total_loop:
  value: 1000
SOPHON_ml_loop:
  value: 1
SOPHON_nl_loop:
  value: 1
SOPHON_fast_lr:
  value: 0.0001
SOPHON_lr:
  value: 0.0001
SOPHON_alpha:
  value: 3.0
SOPHON_beta:
  value: 5.0
SOPHON_adaptation_steps:
  value: 50
SOPHON_maml_loss_func:
  # value: 'inverse_loss'
  value: 'kl_loss'